apiVersion: v1
kind: Namespace
metadata:
  name: weft-finance
  labels:
    name: weft-finance
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weft-landing-config
  namespace: weft-finance
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  APP_NAME: "Weft Finance Landing"
  APP_VERSION: "1.0.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: weft-landing-secrets
  namespace: weft-finance
type: Opaque
data:
  # Add any secrets here in base64 format
  # Example: API_KEY: <base64-encoded-api-key>
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: weft-landing-pdb
  namespace: weft-finance
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: weft-landing
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: weft-landing-hpa
  namespace: weft-finance
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weft-landing-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: weft-landing-network-policy
  namespace: weft-finance
spec:
  podSelector:
    matchLabels:
      app: weft-landing
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
